export const emailsDataMockData = {
    "items": [
        {
            id: 'e101',
            to: 'momo@momo.com',
            from: 'user@appsus.com',
            subject: 'Meeting Tomorrow',
            body: `Let's discuss the agenda for our meeting tomorrow. Lost in the pages of an ancient tome, the scholar delved into the mysteries of a bygone era. Dust particles danced in the dim candlelight, creating an atmosphere of reverence for the knowledge hidden within those weathered pages. Each word held the weight of centuries, whispering secrets to those willing to listen.`,
            isRead: false,
            sentAt: 1678133930594,
            removedAt: null,
            isStarred: false,
            label: 'promotions',
        },
        {
            id: 'e102',
            to: 'user@appsus.com',
            from: 'momo@momo.com',
            subject: 'Weekend Plans',
            body: 'Any exciting plans for the weekend? Laughter echoed through the family home as the children played in the backyard, their imaginations running wild. The aroma of freshly baked cookies wafted from the kitchen, enticing everyone to gather around the table for a moment of shared joy and simple pleasures.',
            isRead: true,
            sentAt: 1678233930594,
            removedAt: null,
            isStarred: false,
            label: 'promotions',
        },
        {
            id: 'e103',
            to: 'user@appsus.com',
            from: 'momo@momo.com',
            subject: 'Project Update',
            body: `Here's the latest update on our ongoing project. In the heart of the bustling city, surrounded by towering skyscrapers and the hum of traffic, there lies a quaint little cafe. Its facade adorned with ivy and a charming sign that reads "Sereni-tea Corner," beckoning passersby to step into a world of tranquility amidst the urban chaos.`,
            isRead: true,
            sentAt: 1678333930594,
            removedAt: 1678233930594,
            isStarred: false,
            label: 'primary',
        },
        {
            id: 'e104',
            to: 'user@appsus.com',
            from: 'momo@momo.com',
            subject: 'Happy Birthday!',
            body: 'Wishing you a fantastic birthday filled with joy and laughter. Under the twinkling stars of a clear night sky, a solitary figure stood on the edge of the cliff, gazing out at the vast ocean below. The rhythmic sound of waves crashing against the rocks echoed the timeless song of nature, a melody that soothed the soul and connected the observer to the cosmic dance of the universe. ',
            isRead: false,
            sentAt: 1678433930594,
            removedAt: null,
            isStarred: false,
            label: 'primary',
        },
        {
            id: 'e105',
            to: 'user@appsus.com',
            from: 'user@appsus.com',
            subject: 'Coffee Chat?',
            body: 'Would you be up for a coffee chat sometime this week?',
            isRead: false,
            sentAt: 1678533930594,
            removedAt: null,
            isStarred: true,
            label: 'promotions',
        },
        {
            id: 'e106',
            to: 'user@appsus.com',
            from: 'user@appsus.com',
            subject: 'New Project Proposal',
            body: 'Exciting new project proposal to discuss. Let me know your thoughts.',
            isRead: false,
            sentAt: 1678633930594,
            removedAt: null,
            isStarred: true,
            label: 'primary',
        },
        {
            id: 'e107',
            to: 'user@appsus.com',
            from: 'jane.smith@example.com',
            subject: 'Meeting Tomorrow',
            body: 'Let\'s discuss the agenda for our meeting tomorrow.',
            isRead: false,
            sentAt: 1678133930594,
            removedAt: null,
            isStarred: false,
            label: ['primary', 'promotions'],
        },
        {
            id: 'e108',
            to: 'user@appsus.com',
            from: 'john.doe@example.com',
            subject: 'Weekend Plans',
            body: 'Any exciting plans for the weekend?',
            isRead: true,
            sentAt: 1678233930594,
            removedAt: null,
            isStarred: false,
            label: ['primary', 'promotions'],
        },
        {
            id: 'e109',
            to: 'user@appsus.com',
            from: 'john.doe@example.com',
            subject: 'Project Update',
            body: 'Here\'s the latest update on our ongoing project.',
            isRead: true,
            sentAt: 1678333930594,
            removedAt: 1678233930594,
            isStarred: false,
            label: ['primary', 'social'],
        },
        {
            id: 'e110',
            to: 'momo@momo.com',
            from: 'john.doe@example.com',
            subject: 'Happy Birthday!',
            body: 'Wishing you a fantastic birthday filled with joy and laughter.',
            isRead: false,
            sentAt: 1678433930594,
            removedAt: null,
            isStarred: false,
            label: ['primary', 'social'],
        },
        {
            id: 'e111',
            to: 'user@appsus.com',
            from: 'jane.smith@example.com',
            subject: 'Coffee Chat?',
            body: 'Would you be up for a coffee chat sometime this week?',
            isRead: false,
            sentAt: 1678533930594,
            removedAt: null,
            isStarred: true,
            label: ['primary', 'social'],
        },
        {
            id: 'e112',
            to: 'momo@momo.com',
            from: 'jane.smith@example.com',
            subject: 'New Project Proposal',
            body: 'Exciting new project proposal to discuss. Let me know your thoughts.',
            isRead: false,
            sentAt: 1678633930594,
            removedAt: null,
            isStarred: true,
            label: ['primary', 'social'],
        },
        {
            id: 'e113',
            to: 'john.doe@example.com',
            from: 'alice.jones@example.com',
            subject: 'Meeting Agenda',
            body: 'Agenda for the upcoming team meeting attached. Please review.',
            isRead: true,
            sentAt: 1678633945678,
            removedAt: null,
            isStarred: false,
            label: ['primary', 'social'],
        },
        {
            id: 'e114',
            to: 'bob@email.com',
            from: 'user@appsus.com',
            subject: 'Weekend Plans',
            body: `Let's plan something fun for the weekend. Any suggestions?`,
            isRead: false,
            sentAt: 1678633961234,
            removedAt: null,
            isStarred: true,
            label: ['primary'],
        },
        {
            id: 'e115',
            to: 'user@appsus.com',
            from: 'sales@company.com',
            subject: 'Product Demo',
            body: 'Exciting new features to showcase in our product demo. Join us!',
            isRead: false,
            sentAt: 1678633987654,
            removedAt: null,
            isStarred: false,
            label: 'social',
        },
        {
            id: 'e116',
            to: 'user@appsus.com',
            from: 'your@email.com',
            subject: 'Weekend Getaway',
            body: `Let's plan a weekend getaway. Any preferences for the destination?`,
            isRead: true,
            sentAt: 1678634009876,
            removedAt: null,
            isStarred: true,
            label: 'social',
        },
        {
            id: 'e117',
            to: 'support@helpdesk.com',
            from: 'user@appsus.com',
            subject: 'Technical Issue',
            body: 'Experiencing technical issues. Need assistance urgently!',
            isRead: false,
            sentAt: 1678634023456,
            removedAt: null,
            isStarred: false,
            label: 'social',
        },
        {
            id: 'e118',
            to: 'marketing@company.com',
            from: 'user@appsus.com',
            subject: 'Marketing Strategy',
            body: 'Review the proposed marketing strategy and provide feedback.',
            isRead: true,
            sentAt: 1678634056789,
            removedAt: null,
            isStarred: true,
            label: 'promotions',
        },
        {
            id: 'e119',
            to: 'user@appsus.com',
            from: 'you@email.com',
            subject: 'Family Reunion',
            body: `Let's plan a family reunion. When are you availabel?`,
            isRead: false,
            sentAt: 1678634087654,
            removedAt: null,
            isStarred: false,
            label: 'promotions',
        },
        {
            id: 'e120',
            to: 'hr@company.com',
            from: 'user@appsus.com',
            subject: 'Job Interview Schedule',
            body: 'Schedule for your upcoming job interview. Be prepared!',
            isRead: true,
            sentAt: 1678634101234,
            removedAt: null,
            isStarred: true,
            label: 'promotions',
        },
        {
            id: 'e121',
            to: 'friend2@email.com',
            from: 'user@appsus.com',
            subject: 'Dinner Plans',
            body: `Let's catch up for dinner this weekend. What do you feel like eating?`,
            isRead: false,
            sentAt: 1678634123456,
            removedAt: null,
            isStarred: false,
            label: 'promotions',
        },
        {
            id: 'e122',
            to: 'user@appsus.com',
            from: 'project.manager@company.com',
            subject: 'Project Update',
            body: 'Latest update on the ongoing project. Check it out!',
            isRead: true,
            sentAt: 1678634156789,
            removedAt: null,
            isStarred: true,
            label: 'promotions',
        },
        {
            id: 'e123',
            to: 'user@appsus.com',
            from: 'your@email.com',
            subject: 'Movie Night',
            body: 'Planning a movie night. Any movie preferences?',
            isRead: false,
            sentAt: 1678634178901,
            removedAt: null,
            isStarred: true,
            label: 'promotions',
        },
        {
            id: 'e124',
            to: 'user@appsus.com',
            from: 'tech.lead@company.com',
            subject: 'Code Review Feedback',
            body: 'Feedback on your recent code submissions. Please address the comments.',
            isRead: true,
            sentAt: 1678634201234,
            removedAt: null,
            isStarred: false,
            label: 'primary',
        },
        {
            id: 'e125',
            to: 'supplier@company.com',
            from: 'user@appsus.com',
            subject: 'Supply Chain Update',
            body: 'Update on the latest supply chain developments. Take a look!',
            isRead: false,
            sentAt: 1678634223456,
            removedAt: null,
            isStarred: true,
            label: 'primary',
        },
        {
            id: 'e126',
            to: 'client2@company.com',
            from: 'user@appsus.com',
            subject: 'Invoice Payment Reminder',
            body: 'Friendly reminder to process the pending invoice payment. Thank you!',
            isRead: true,
            sentAt: 1678634256789,
            removedAt: null,
            isStarred: false,
            label: 'primary',
        },
        {
            id: 'e127',
            to: 'friend4@email.com',
            from: 'user@appsus.com',
            subject: 'Book Club Meeting',
            body: `Book club meeting this weekend. Don't forget to read the assigned chapters!`,
            isRead: false,
            sentAt: 1678634289012,
            removedAt: null,
            isStarred: false,
            label: 'primary',
        },
        {
            id: 'e128',
            to: 'support2@helpdesk.com',
            from: 'user@appsus.com',
            subject: 'Technical Assistance Needed',
            body: 'Encountering technical issues again. Urgent assistance required!',
            isRead: true,
            sentAt: 1678634312345,
            removedAt: null,
            isStarred: true,
            label: 'primary',
        },
        {
            id: 'e129',
            to: 'user@appsus.com',
            from: 'you@email.com',
            subject: 'Birthday Celebration Plans',
            body: 'Planning a surprise birthday celebration. Need your input!',
            isRead: false,
            sentAt: 1678634345678,
            removedAt: null,
            isStarred: false,
            label: 'primary',
        },
        {
            id: 'e130',
            to: 'user@appsus.com',
            from: 'manager@company.com',
            subject: 'Team Building Event',
            body: 'Details about the upcoming team-building event. Save the date!',
            isRead: true,
            sentAt: 1678634378901,
            removedAt: null,
            isStarred: true,
            label: 'social',
        },
        {
            id: 'e131',
            to: 'friend5@email.com',
            from: 'user@appsus.com',
            subject: 'Weekend Hike',
            body: 'Interested in a weekend hike? Let me know your availability.',
            isRead: false,
            sentAt: 1678634412345,
            removedAt: null,
            isStarred: false,
            label: 'social',
        },
        {
            id: 'e132',
            to: 'team2@project.com',
            from: 'user@appsus.com',
            subject: 'Client Meeting Agenda',
            body: 'Agenda for the upcoming client meeting attached. Prepare accordingly.',
            isRead: true,
            sentAt: 1678634445678,
            removedAt: null,
            isStarred: true,
            label: 'social',
        },

    ]
}
