export const emailsDataMockData = {
    "items": [
        {
            id: 'e101',
            to: 'momo@momo.com',
            from: 'user@appsus.com',
            subject: 'Meeting Tomorrow',
            body: `Let's discuss the agenda for our meeting tomorrow.`,
            isRead: false,
            sentAt: 1678133930594,
            removedAt: null,
            isStarred: false,
            labels: [],
        },
        {
            id: 'e102',
            to: 'user@appsus.com',
            from: 'momo@momo.com',
            subject: 'Weekend Plans',
            body: 'Any exciting plans for the weekend?',
            isRead: true,
            sentAt: 1678233930594,
            removedAt: null,
            isStarred: false,
            labels: [],
        },
        {
            id: 'e103',
            to: 'user@appsus.com',
            from: 'momo@momo.com',
            subject: 'Project Update',
            body: `Here's the latest update on our ongoing project.`,
            isRead: true,
            sentAt: 1678333930594,
            removedAt: 1678233930594,
            isStarred: false,
            labels: [],
        },
        {
            id: 'e104',
            to: 'user@appsus.com',
            from: 'momo@momo.com',
            subject: 'Happy Birthday!',
            body: 'Wishing you a fantastic birthday filled with joy and laughter.',
            isRead: false,
            sentAt: 1678433930594,
            removedAt: null,
            isStarred: false,
            labels: [],
        },
        // {
        //     id: 'e105',
        //     to: 'momo@momo.com',
        //     from: 'user@appsus.com',
        //     subject: 'Coffee Chat?',
        //     body: 'Would you be up for a coffee chat sometime this week?',
        //     isRead: false,
        //     sentAt: 1678533930594,
        //     removedAt: null,
        //     isStarred: false,
        //     labels: [],
        // },
        // {
        //     id: 'e106',
        //     to: 'momo@momo.com',
        //     from: 'user@appsus.com',
        //     subject: 'New Project Proposal',
        //     body: 'Exciting new project proposal to discuss. Let me know your thoughts.',
        //     isRead: false,
        //     sentAt: 1678633930594,
        //     removedAt: null,
        //     isStarred: false,
        //     labels: [],
        // },
    ]
}
