export const emailsDataMockData = {
    "items": [
        {
            id: 'e101',
            to: 'momo@momo.com',
            from: 'user@appsus.com',
            subject: 'Meeting Tomorrow',
            body: `Let's discuss the agenda for our meeting tomorrow. Lost in the pages of an ancient tome, the scholar delved into the mysteries of a bygone era. Dust particles danced in the dim candlelight, creating an atmosphere of reverence for the knowledge hidden within those weathered pages. Each word held the weight of centuries, whispering secrets to those willing to listen.`,
            isRead: false,
            sentAt: 1678133930594,
            removedAt: null,
            isStarred: false,
            labels: [],
        },
        {
            id: 'e102',
            to: 'user@appsus.com',
            from: 'momo@momo.com',
            subject: 'Weekend Plans',
            body: 'Any exciting plans for the weekend? Laughter echoed through the family home as the children played in the backyard, their imaginations running wild. The aroma of freshly baked cookies wafted from the kitchen, enticing everyone to gather around the table for a moment of shared joy and simple pleasures.',
            isRead: true,
            sentAt: 1678233930594,
            removedAt: null,
            isStarred: false,
            labels: [],
        },
        {
            id: 'e103',
            to: 'user@appsus.com',
            from: 'momo@momo.com',
            subject: 'Project Update',
            body: `Here's the latest update on our ongoing project. In the heart of the bustling city, surrounded by towering skyscrapers and the hum of traffic, there lies a quaint little cafe. Its facade adorned with ivy and a charming sign that reads "Sereni-tea Corner," beckoning passersby to step into a world of tranquility amidst the urban chaos.`,
            isRead: true,
            sentAt: 1678333930594,
            removedAt: 1678233930594,
            isStarred: false,
            labels: [],
        },
        {
            id: 'e104',
            to: 'user@appsus.com',
            from: 'momo@momo.com',
            subject: 'Happy Birthday!',
            body: 'Wishing you a fantastic birthday filled with joy and laughter. Under the twinkling stars of a clear night sky, a solitary figure stood on the edge of the cliff, gazing out at the vast ocean below. The rhythmic sound of waves crashing against the rocks echoed the timeless song of nature, a melody that soothed the soul and connected the observer to the cosmic dance of the universe. ',
            isRead: false,
            sentAt: 1678433930594,
            removedAt: null,
            isStarred: false,
            labels: [],
        },
        // {
        //     id: 'e105',
        //     to: 'momo@momo.com',
        //     from: 'user@appsus.com',
        //     subject: 'Coffee Chat?',
        //     body: 'Would you be up for a coffee chat sometime this week?',
        //     isRead: false,
        //     sentAt: 1678533930594,
        //     removedAt: null,
        //     isStarred: false,
        //     labels: [],
        // },
        // {
        //     id: 'e106',
        //     to: 'momo@momo.com',
        //     from: 'user@appsus.com',
        //     subject: 'New Project Proposal',
        //     body: 'Exciting new project proposal to discuss. Let me know your thoughts.',
        //     isRead: false,
        //     sentAt: 1678633930594,
        //     removedAt: null,
        //     isStarred: false,
        //     labels: [],
        // },
    ]
}
